### PR TITLE
Ubuntu distro updates

### PR DESCRIPTION
**Pull request by dmarkow**
Ubuntu 20.10 (groovy) has reached end of life. Using this image now results in `apt update` errors as of a couple days ago. Updating it to use the current interim release, 21.10 (impish) instead. Also updating the LTS releases to the latest builds.

Another option would be to just use code names without the dates, which Ubuntu keeps updated to always point to the latest builds, e.g. `ubuntu:impish` is the same as `ubuntu:impish-20211102`

### CODE REVIEW

**Comment by ericmj** [comment]
We also need a new dockerfile for impish, you can find the existing files here: https://github.com/hexpm/bob/tree/main/priv/scripts/docker.

Please also build an image against the oldest and newest supported OTP versions locally and check that you can start ssl by running: `application:ensure_all_started(ssl).` or `Application.ensure_all_started(:ssl)`.

> Another option would be to just use code names without the dates, which Ubuntu keeps updated to always point to the latest builds, e.g. ubuntu:impish is the same as ubuntu:impish-20211102

We don't want to do that because we want the user to know exactly what image they are getting.

**Comment by dmarkow** [comment]
Thanks for the quick feedback! Didn't realize there were additional files, I'll dig in when I have a little more time.

> We don't want to do that because we want the user to know exactly what image they are getting.

I had a feeling this was the case.

**Comment by dmarkow** [comment]
@ericmj I just renamed the groovy file to impish (since you can't even run the build on groovy anymore now that it's end of life, so I'm really just swapping in the latest interim release)

How do I determine what the oldest supported OTP version is? I see some code mentioning OTP-17.5, but `docker_checker.ex` excludes OTP 17 through 19 on several distros. For example, the oldest build at https://hub.docker.com/r/hexpm/erlang/tags?page=1&name=focal&ordering=-last_updated for focal/20.04 is OTP-20. I can't get anything lower than OTP-20 to build on ubuntu 21.10 (they all fail with `hipe/hipe_x86_signal.c:281:26: error: storage size of 'my_sigstack' isn't constant`), but don't want to spend time debugging if I don't need to. 20.0 through 24.2 seem to work fine:

```
± docker run -it hexpm/erlang-amd64:20.0-ubuntu-impish-20211102
root@9d0a8b9d362b:/# erl
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}

± docker run -it hexpm/erlang-amd64:24.2-ubuntu-impish-20211102
root@0115379f40a3:/# erl
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Eshell V12.2  (abort with ^G)
1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}
```
